version: "3.8"
x-app:
  &default-app
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

services:
  nginx:
    <<: *default-app
    container_name: skypaper-nginx
    build:
      context: "./docker/nginx"
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT_OUT}:${NGINX_PORT}"
    depends_on:
      - backend
      - frontend
    volumes:
      # this will mount the backend folder which contains the code to the docker container
      - ./services/backend:/var/www/backend:delegated
      # this will mount the nginx logs so that you can check the logs for errors,
      # without logging into the container
      - ./logs/nginx/:/var/log/nginx:delegated
      # this will create the server config to serve the backend
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/backend.conf:delegated

  backend:
    <<: *default-app
    container_name: skypaper-backend
    build:
      context: "./docker/php"
      dockerfile: Dockerfile
    volumes:
      # this will mount the backend folder which contains the code to the docker container
      - ./services/backend:/var/www/backend:delegated
      # this will mount the custom `.ini` to the container
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro

  frontend:
    <<: *default-app
    build: 
      context: "./services/frontend"
      dockerfile: dev.Dockerfile
    container_name: skypaper-frontend
    ports:
      - "${DOCKER_FRONTEND_PORT_OUT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    volumes:
      # this will mount the frontend folder which contains the code to the docker container
      - ./services/frontend:/var/www/frontend
    environment:
      - FRONTEND_PORT=${DOCKER_FRONTEND_PORT_OUT}
      - BACKEND_URL=${BACKEND_DOMAIN}:${DOCKER_NGINX_PORT_OUT}